apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "exit-node.fullname" . }}
  labels:
    {{- include "exit-node.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "exit-node.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "exit-node.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "exit-node.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: hopr
          securityContext:
            {{- toYaml .Values.hopr.securityContext | nindent 12 }}
          image: "{{ .Values.hopr.image.repository }}:{{ .Values.hopr.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.hopr.image.pullPolicy }}
          {{- if .Values.env }}
          env:
          {{- range $value, $key := .Values.env }}
            - name: {{ $key.name }}
              value: {{ $key.value | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.rpch.envFrom }}
          envFrom:
          {{- range $value := .Values.rpch.envFrom }}
            {{- if (eq .type "configmap") }}
            - configMapRef:
                name: {{ .name }}
            {{- end }}
            {{- if (eq .type "secret") }}
            - secretRef:
                name: {{ .name }}
            {{- end }}
          {{- end }}
          {{- end }}
          {{- with .Values.service.ports }}
          ports:
            {{- range . }}
            - containerPort: {{ .port }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.hopr.resources | nindent 12 }}

        - name: rpch
          securityContext:
            {{- toYaml .Values.rpch.securityContext | nindent 12 }}
          image: "{{ .Values.rpch.image.repository }}:{{ .Values.rpch.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.rpch.image.pullPolicy }}
          {{- if .Values.rpch.envFrom }}
          envFrom:
          {{- range $value := .Values.rpch.envFrom }}
            {{- if (eq .type "configmap") }}
            - configMapRef:
                name: {{ .name }}
            {{- end }}
            {{- if (eq .type "secret") }}
            - secretRef:
                name: {{ .name }}
            {{- end }}
          {{- end }}
          {{- end }}
          {{- with .Values.rpch.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.rpch.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
