apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "exit-node.fullname" . }}-hopr-data
  labels:
    {{- include "exit-node.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.hopr.persistence.data.size }}