apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "exit-node.fullname" . }}-rpch-identity
  labels:
    {{- include "exit-node.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.rpch.persistence.identity.size }}