apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "exit-node.fullname" . }}
  labels:
    {{- include "exit-node.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: 10Gi