apiVersion: v1
kind: Service
metadata:
  name: {{ include "exit-node.fullname" . }}
  labels:
    {{- include "exit-node.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  selector:
    {{- include "exit-node.selectorLabels" . | nindent 4 }}
