replicaCount: 1

image:
  repository: sitilge/discovery-platform
  pullPolicy: IfNotPresent
  tag: ""

env: {}
envFrom: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3020
  name: "main"

ingress:
  enabled: true
  className: ""
  annotations:
    cert-manager.io/issuer: rpch
  hosts:
    - host: discovery.rpch.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: discovery.rpch.net-tls
      hosts:
        - discovery.rpch.net

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80