replicaCount: 1

service:
  ports:
    - port: 3000
      name: "3000"
    - port: 8080
      name: "8080"
    - port: 9091
      name: "9091"

hopr:
  image:
    repository: gcr.io/hoprassociation/hoprd
    pullPolicy: IfNotPresent
    tag: ""

  env: {}

  resources: {}

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

rpch:
  image:
    repository: sitilge/exit-node
    pullPolicy: IfNotPresent
    tag: ""

  env: {}

  resources: {}

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80