apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: funding-service-staging
  namespace: argocd
spec:
  project: default
  source:
    #TODO - do not hardcode
    repoURL: https://github.com/Rpc-h/infrastructure
    targetRevision: staging
    path: charts/funding-service
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            image:
              repository: sitilge/funding-service
              tag: a6d518b
            envFrom:
              - type: secret
                name: funding-service-staging
            env:
              - name: "PORT"
                value: "3010"
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
