apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: funding-service-testing
  namespace: argocd
spec:
  project: default
  source:
    #TODO - do not hardcode
    repoURL: https://github.com/Rpc-h/infrastructure
    targetRevision: testing
    path: charts/funding-service
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            image:
              tag: "a6d518b"
            env:
              - name: "BRANCH"
                value: "MAIN"
              - name: "SECRET_KEY"
                value: ""
              - name: "WALLET_PRIV_KEY"
                value: ""
              - name: "DB_CONNECTION_URL"
                value: ""
              - name: "SMART_CONTRACT_ADDRESS"
                value: ""
              - name: "PORT"
                value: "3020"
  destination:
    server: https://kubernetes.default.svc
    namespace: testing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
