apiVersion: v1
kind: Service
metadata:
  name: {{ include "funding-service.fullname" . }}
  labels:
    {{- include "funding-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: {{ .Values.service.name }}
      targetPort: {{ .Values.service.name }}
      protocol: TCP
  selector:
    {{- include "funding-service.selectorLabels" . | nindent 4 }}
