apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discovery-platform-staging
  namespace: argocd
spec:
  project: default
  source:
    #TODO - do not hardcode
    repoURL: https://github.com/Rpc-h/infrastructure
    targetRevision: staging
    path: charts/discovery-platform
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            image:
              repository: sitilge/discovery-platform
              tag: a6d518b
            envFrom:
              - type: secret
                name: discovery-platform-production
            env:
              - name: "FUNDING_SERVICE_URL"
                value: "http://funding-service.production:3010"
            ingress:
              enabled: true
              className: ""
              annotations:
                cert-manager.io/cluster-issuer: rpch-tech
              hosts:
                - host: discovery.rpch.tech
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
              tls:
                - secretName: discovery.rpch.tech-tls
                  hosts:
                    - discovery.rpch.tech
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
