apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discovery-platform
  namespace: argocd
spec:
  project: default
  source:
    #TODO - do not hardcode
    repoURL: https://github.com/Rpc-h/infrastructure
    targetRevision: main
    path: charts/discovery-platform
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            image:
              repository: sitilge/discovery-platform
              tag: a6d518b
            envFrom:
                type: secret
                name: discovery-platform
            env:
              - name: "FUNDING_SERVICE_URL"
                value: "http://funding-service.production:3010"
              - name: "PORT"
                value: "3020"
              - name: "NODE_ENV"
                value: "development"
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
