apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discovery-platform
  namespace: production
spec:
  encryptedData:
    DB_CONNECTION_URL: AgCxx66EuyQO7KD1SjR+UnKfbmFqXRQUQCibQtik+6e7ew4J5J3Oc5Qim4afZ+7tw0n4SrOtOOhkGJSbJcmjEjL3FBSeUJMyBE76ma7QTOEL7yuPa9kE421yrQFmbDn16BqUAw53x82keKLp5FM8pTeSRyF6Yh8Qfte5HkuVPbsqF87carbegu5zVs+H0gwlNvjPDsMII6Whqi4MD6Ve1Hb//MaOd5gGslK9E873A4CUHxjgelbKK2NWmevKet9oEPkatnC1FbBKiCI+k4uxCFEuxPrCmwdfCClrUoOJaJg7kUAYl9tktMc8Cff0xekKRBTwFPMBipLk0iu5QIfQtpbtJvY5gV/lJC9us7DveMLkjBeXIRmloOXoybFal5m1q2E04cnKFOSRoRKT57fYzNoMVZM4x86SRXOWdhxR1eDiTh7DX2glXBJp/rmq87ZrTBJ2HOhqe42PuZamibWDPqM9uL8gVicNr7yUniIQ+YUqzmHOBIw0vzNrTYLllONqzwEDtUUpr9qnkce7+E7XfxC9M1ifYNrAWCVu47juXUnDfJLFk4sA/Bg4aazyqEK3IMXuRg7XuK0UnDMaujFbZZaQaLibKrTSl8sTREr/I/zf4FqlxBnlWvkPWMpoygMoRTUbYE0jZY2qkR1Ia/ScF7sgyOoXzEEJ23F6nDqPUJnGCYfxoxMo2I3OQvNiFKtfiwUHpqn1yuLhHX8k
  template:
    metadata:
      creationTimestamp: null
      name: discovery-platform
      namespace: production