- name: Install Server
  gather_facts: true
  hosts: all
  become: true
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
          - git
          - tmux
        state: latest
        update_cache: true
      tags:
        - install
    - name: Add signing key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/debian/gpg"
        state: present
      tags:
        - install
    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable"
        state: present
        filename: docker
      tags:
        - install
    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce=5:24.0.0-1~debian.11~bullseye
          - docker-ce-cli=5:24.0.0-1~debian.11~bullseye
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true
      tags:
        - install
    - name: Install Promtail
      ansible.builtin.include_role:
        name: patrickjahns.promtail
      vars:
        promtail_config_file: /etc/promtail/config.yaml
        promtail_system_user: root
        promtail_system_group: root
      tags:
        - promtail
    - name: Configure Promtail
      template:
        src: promtail-config.yaml.j2
        dest: /etc/promtail/config.yaml
      tags:
        - promtail
