- name: Install playbook
  gather_facts: false
  hosts: all
  become: true
  strategy: free
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
          - git
        state: latest
        update_cache: true

    - name: Add signing key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/debian/gpg"
        state: present

    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable"
        state: present
        filename: docker

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce=5:24.0.0-1~debian.11~bullseye
          - docker-ce-cli=5:24.0.0-1~debian.11~bullseye
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: Pull the repo
      ansible.builtin.git:
        repo: https://github.com/Rpc-h/RPCh
        dest: /root/RPCh

    - name: Start all services
      ansible.builtin.shell:
        chdir: /root/RPCh/apps/exit-node
        cmd: docker compose up -d --build
      register: output

    - name: Show results
      ansible.builtin.debug:
        var: output