- name: Restart entry Nodes
  gather_facts: false
  hosts: entry_node,exit_node,entry_node_a,entry_node_b,entry_node_c,exit_node_a,exit_node_b,exit_node_c
  become: true
  vars:
    clean_db: false
  tags:
    - entry_node
  tasks:
    - name: Stop Hoprd service
      ansible.builtin.service:
        name: "hoprd.service"
        state: stopped
        enabled: true

    - name: Remove database
      ansible.builtin.shell:
        cmd: rm -rf /opt/hoprd/db
      when: clean_db == 'true'

    - name: Start Hoprd service
      ansible.builtin.service:
        name: "hoprd.service"
        state: started
        enabled: true

    - name: Pause for 5 minutes allow hoprd start
      ansible.builtin.pause:
        minutes: 5
      tags:
        - pause

- name: Restart exit Nodes
  gather_facts: false
  hosts: exit_node,exit_node_a,exit_node_b,exit_node_c
  become: true
  tasks:
    - name: Restart Exit Node service
      ansible.builtin.service:
        name: "exit-node.service"
        state: restarted
        enabled: true


