- name: Restart entry Nodes
  gather_facts: false
  hosts: entry_node,phttp_exit_app,entry_node_a,entry_node_b,entry_node_c,phttp_exit_app_a,phttp_exit_app_b,phttp_exit_app_c
  become: true
  vars:
    clean_db: false
  tags:
    - entry_node
  tasks:
    - name: Stop Hoprd service
      ansible.builtin.service:
        name: "hoprd.service"
        state: stopped
        enabled: true

    - name: Remove database
      ansible.builtin.shell:
        cmd: rm -rf /opt/hoprd/db
      when: clean_db == 'true'

    - name: Start Hoprd service
      ansible.builtin.service:
        name: "hoprd.service"
        state: started
        enabled: true

    - name: Pause for 3 minutes allow hoprd start
      ansible.builtin.pause:
        minutes: 3
      tags:
        - pause

- name: Restart pHTTP exit apps
  gather_facts: false
  hosts: phttp_exit_app,phttp_exit_app_a,phttp_exit_app_b,phttp_exit_app_c
  become: true
  tasks:
    - name: Restart pHTTP exit app service
      ansible.builtin.service:
        name: "phttp_exit_app.service"
        state: restarted
        enabled: true
