- name: Restart playbook
  gather_facts: false
  hosts: all
  become: true
  strategy: free
  tasks:
    - name: Stop all services
      ansible.builtin.shell:
        chdir: /root/RPCh/apps/exit-node
        cmd: docker compose down
      register: output

    - name: Show results
      ansible.builtin.debug:
        var: output

    # - name: Remove database
    #   ansible.builtin.shell:
    #     cmd: rm -rf /opt/hoprd/db
    #   tags:
    #     remove-db

    - name: Start all services
      ansible.builtin.shell:
        chdir: /root/RPCh/apps/exit-node
        cmd: docker compose up -d --build
      register: output

    - name: Show results
      ansible.builtin.debug:
        var: output