- name: Restart entry Nodes
  gather_facts: false
  hosts: entry-node,exit-node
  become: true
  vars:
    clean_db: false
  tasks:
    - name: Stop Hoprd service
      ansible.builtin.service:
        name: "hoprd.service"
        state: stopped
        enabled: true

    - name: Remove database
      ansible.builtin.shell:
        cmd: rm -rf /opt/hoprd/db
      when: clean_db == 'true'

    - name: Start Hoprd service
      ansible.builtin.service:
        name: "hoprd.service"
        state: started
        enabled: true

- name: Restart exit Nodes
  gather_facts: false
  hosts: exit-node
  become: true
  tasks:
    - name: Restart Exit Node service
      ansible.builtin.service:
        name: "exit-node.service"
        state: restarted
        enabled: true


