- name: Show Environment Config
  gather_facts: true
  hosts: all
  become: true
  strategy: free
  tasks:
    - name: "Read variables"
      ansible.builtin.set_fact:
        chain_id: '100'
        peer_id: "{{ (lookup('ansible.builtin.file', 'files/' + environment_name + '/' + inventory_hostname + '/hoprd.json') | from_json).get('.hoprd.id').get('peer_id') }}"
        native_address: "{{ (lookup('ansible.builtin.file', 'files/' + environment_name + '/' + inventory_hostname + '/hoprd.json') | from_json).get('.hoprd.id').get('native_address') }}"
        hoprd_api_endpoint: "http://{{ ansible_default_ipv4.address }}:3001"
        rpch_public_key: 'tbd'
    - name: "Build JSON"
      ansible.builtin.set_fact:
        rpch_properties: '{ "chain_id": "100", "peer_id": "{{ peer_id }}", "native_address":  "{{ native_address }}", "hoprd_api_endpoint": "{{ hoprd_api_endpoint }}", "rpch_public_key": "{{ rpch_public_key }}" }'
    - name: Print variables
      debug:
        var: rpch_properties
