---

# SSH configuration
ansible_ssh_common_args: "-F ./hcloud_ssh_config_rpch_staging"

environment_name: "staging"

hoprd_version: 2.1.0-rc.3-pr.6088
rpch_exit_node_version: 1.2.0

hoprd_config: |
  hopr:
    chain:
      network: rotsee
      provider: https://primary.gnosis-chain.rpc.hoprtech.net
    strategy:
      on_fail_continue: true
      allow_recursive: false
      finalize_channel_closure: true
      strategies:
        - !Promiscuous
          max_channels: 10
          network_quality_threshold: 0.5
          new_channel_stake: "1000000 HOPR"
          minimum_node_balance: "10000000 HOPR"
          min_network_size_samples: 20
          enforce_max_channels: true
          minimum_peer_version: ">=2.0.0"
        - !AutoFunding
          funding_amount: "1000000 HOPR"
          min_stake_threshold: "100000 HOPR"
        - !Aggregating
          aggregation_threshold: 100000
          unrealized_balance_ratio: 0.9
          aggregation_timeout: 60
          aggregate_on_channel_close: true
        - !AutoRedeeming
          redeem_only_aggregated: True
