# SSH configuration
ansible_ssh_common_args: "-F ./hcloud_ssh_config_rpch_production"

environment_name: "prod"

hoprd_version: 2.1.0
hoprd_network: dufour
# rpch_exit_node_version: 1.2.0

hoprd_config: |
  hopr:
    chain:
      announce: true
      network: dufour
      provider: https://gnosis.rpc-provider.prod.hoprnet.link
    strategy:
      on_fail_continue: true
      allow_recursive: false
      strategies:
        - !Promiscuous
          max_channels: 10
          network_quality_threshold: 0.5
          new_channel_stake: "1000000 HOPR"
          minimum_node_balance: "10000000 HOPR"
          min_network_size_samples: 20
          enforce_max_channels: true
          minimum_peer_version: ">=2.0.0"
        - !AutoFunding
          funding_amount: "1000000 HOPR"
          min_stake_threshold: "100000 HOPR"
        - !Aggregating
          aggregation_threshold: 330
          unrealized_balance_ratio: 0.95
          aggregation_timeout: 60
          aggregate_on_channel_close: true
        - !AutoRedeeming
          redeem_only_aggregated: true
          on_close_redeem_single_tickets_value_min: "2000000000000000000 HOPR"
        - !ClosureFinalizer
          max_closure_overdue: 3600
