apiVersion: v1
data:
  users_database.yaml: dXNlcnM6CiAgbWFydGlucy5lZ2xpdGlzOgogICAgZGlzcGxheW5hbWU6ICJNYXJ0aW5zIEVnbGl0aXMiCiAgICBwYXNzd29yZDogIiRhcmdvbjJpZCR2PTE5JG09NjU1MzYsdD0zLHA9NCRYeFRENFQrZkdwRko4aVcrS1pDbERRJDBkUld0eC9TT2dBT25WOW11NEpJZWdtZ3QwRXlYeFJXc1hZR0hTV3dCZDQiCiAgICBlbWFpbDogbWFydGlucy5lZ2xpdGlzQGhvcHJuZXQub3JnCiAgICBncm91cHM6CiAgICAgIC0gYWRtaW5zCiAgc3RldmVuLm5vbmk6CiAgICBkaXNwbGF5bmFtZTogIlN0ZXZlbiBOb25pIgogICAgcGFzc3dvcmQ6ICIkYXJnb24yaWQkdj0xOSRtPTY1NTM2LHQ9MyxwPTQkVCtQS1BYL2JiU0ljY0tIYVo3dFZUQSRZKzJnNmZkbE1lRmFUZmZzUmRDK0ZoeGRJSXEyM0hCWjlmRWFHcENNYTZZIgogICAgZW1haWw6IHN0ZXZlbi5ub25pQGhvcHJuZXQub3JnCiAgICBncm91cHM6CiAgICAgIC0gYWRtaW5zCg==
kind: Secret
metadata:
  creationTimestamp: null
  name: authelia-users
  namespace: authelia
